// Note: this file is generated by `script/generate-regex.js`
export const insensitive =
  /^((?:i\.(?:z\.)?g\.s|p\.s|ok|fu)t|a(?:anw\.vnw|r(?:bo|t)|ug|pr|lg|f[bdkz]|dj|l)|(?:ov\.cmp|uits|exc|vg)l|(?:onov\.w|bn)w|bez\.vnw|i(?:n(?:tern|cl|g)|[dr])|(?:pseu|(?:sy|w)n)d|(?:voor|en)z|t(?:elw|ab|k)|re(?:sp|[df])|p(?:ro[fv]|l[mv]|a[gr]|p)|(?:pen|ko|ja)n|s(?:pe|o)c|febr|(?:sep|za|mr)t|c(?:onf|at)|b(?:i(?:j[lvz]|bl)|lz|[rvw])|(?:mev|j(?:kv|h)|bet|ve|dh)r|vrij|tel|inc|feb|sep|w(?:oe|w)|v(?:n[lw]|s)|znw|se?c|o(?:p[mp]|ng)|n(?:r[os]|ov|l)|zgn|m(?:l[dn]|in|ej|ax|[vw])|l(?:td|[ln])|j(?:u[ln]|[lr])|obl|g(?:ld|e[bhmtz]|r)|f(?:am|[lr])|e(?:xx|vt|tc|[dm])|d(?:rs|ir|e[cl]|[os])|(?:or|fi)g|wo|vr|zn|sp|n[or]|zg|m[ai]|lt|ob|fa|d[ir]|za|mr|ca|zo|kt)$/

export const sensitive =
  /^(Parl\.St|Zr\.Ms|H(?:r\.Ms|erv|zn)|(?:[nv]\.Ch|Sec|N\.B|Mg)r|N(?:\.-I|e[dh]|dl|m)|Pres|Gebr|(?:Z\.E|Nu)m|[UW]ed|Atm|Nd|Zr|Hr|S[rt]|Rb|[JV]z)$/
